
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nahit
 */
public class receteler extends javax.swing.JFrame {

    /**
     * Creates new form receteler
     */
    public receteler() {
        initComponents();
                 Toolkit toolkit = getToolkit();
        Dimension dim = toolkit.getScreenSize();
        setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        setTitle("Reçete Ekranı");
    }
    
    
    public Object item = null;
    
    
     public Statement statement = null;
    
     public PreparedStatement preparedstatement= null;
     
     public  ResultSet resultset = null;
     
     Database_Connect islem = new Database_Connect();
        
     public Connection conn = islem.con;
     
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        recete_kodu_field = new javax.swing.JTextField();
        recete_adi_field = new javax.swing.JTextField();
        ekle_buton = new javax.swing.JButton();
        sil_buton = new javax.swing.JButton();
        guncelle_buton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        getir_buton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Recete Kodu");

        jLabel2.setText("Recete Adi");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, recete_adi_field, org.jdesktop.beansbinding.ObjectProperty.create(), recete_kodu_field, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        recete_kodu_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recete_kodu_fieldActionPerformed(evt);
            }
        });
        recete_kodu_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                recete_kodu_fieldKeyTyped(evt);
            }
        });

        recete_adi_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recete_adi_fieldActionPerformed(evt);
            }
        });
        recete_adi_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                recete_adi_fieldKeyTyped(evt);
            }
        });

        ekle_buton.setText("Ekle");
        ekle_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle_butonActionPerformed(evt);
            }
        });

        sil_buton.setText("Sil");
        sil_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_butonActionPerformed(evt);
            }
        });

        guncelle_buton.setText("Güncelle");
        guncelle_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelle_butonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Recete Kodu", "Recete Adi"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getir_buton.setText("Getir");
        getir_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getir_butonActionPerformed(evt);
            }
        });

        jButton1.setText("Geri");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nahit\\Documents\\NetBeansProjects\\Eczane_Yönetim_Sistemi\\iconlar\\prescription_icon_2-512.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(recete_kodu_field, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(recete_adi_field)))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ekle_buton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(39, 39, 39)
                            .addComponent(guncelle_buton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sil_buton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(getir_buton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ekle_buton)
                            .addComponent(sil_buton)
                            .addComponent(getir_buton)
                            .addComponent(guncelle_buton))
                        .addGap(68, 68, 68)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(recete_kodu_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(recete_adi_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recete_kodu_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recete_kodu_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recete_kodu_fieldActionPerformed

    private void recete_adi_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recete_adi_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recete_adi_fieldActionPerformed

    private void ekle_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle_butonActionPerformed
       
        String recete_kodu=recete_kodu_field.getText().toUpperCase();
        String recete_tipi=recete_adi_field.getText().toUpperCase();
        
        String sorgu = " insert into receteler"
                 + " (recete_kodu,recete_tipi)"
                 + " values (?, ?)";
        
        
        try
        {

            preparedstatement=conn.prepareStatement(sorgu);

            preparedstatement.setString(1,recete_kodu);
            preparedstatement.setString(2,recete_tipi);

            preparedstatement.execute();

        }
                       
       
         
         catch (SQLException ex) 
         {
             
            String hata_mesajı = ex.getMessage();
            
            boolean pk_kontrol = hata_mesajı.contains("PK");    //Primary Key
             
            boolean null_kontrol = hata_mesajı.contains("NULL");

            if(pk_kontrol == true)
            {
             JOptionPane.showMessageDialog(this, "Girdiğiniz recete kodu kayitlarda mevcuttur!","UYARI",JOptionPane.WARNING_MESSAGE);

             recete_kodu_field.requestFocus();

             return;
            }
            
            else if (null_kontrol)
            {
               
             JOptionPane.showMessageDialog(this, "Recete kodu boş geçilemez!","UYARI",JOptionPane.WARNING_MESSAGE);

             recete_kodu_field.requestFocus();

             return;
                       
            }
                  
         }
         
        JOptionPane.showMessageDialog(this,"Kayit Başarıyla Eklendi!");
        
        recete_adi_field.setText("");
        recete_kodu_field.setText("");
        
    }//GEN-LAST:event_ekle_butonActionPerformed

    private void getir_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getir_butonActionPerformed
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        model.setRowCount(0);
        
        String sorgu = " Select recete_kodu,recete_tipi From receteler order by recete_kodu";

        String recete_kodu;
        String recete_tipi;
        
        
        
        try
        {
            
            statement=conn.createStatement();
            
            resultset = statement.executeQuery(sorgu);
            
            while(resultset.next())
            {
             
               recete_kodu=resultset.getString("recete_kodu");
               recete_tipi=resultset.getString("recete_tipi");
               
               Object [] eklenecek = {recete_kodu,recete_tipi};
               
               model.addRow(eklenecek);
            
                
            }
            
            resultset.close();
            
        }
                       
       
         
         catch (SQLException ex) 
         {
             
           
            ex.printStackTrace();
                  
         }
        
        
        
        
        
    }//GEN-LAST:event_getir_butonActionPerformed

    private void guncelle_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelle_butonActionPerformed
       
        String recete_kodu=recete_kodu_field.getText().toUpperCase();
        String recete_tipi=recete_adi_field.getText().toUpperCase();
        
        String sorgu = " UPDATE receteler set recete_tipi=? WHERE recete_kodu=?";
        
        if(recete_kodu.equals("null"))
        {
            
             JOptionPane.showMessageDialog(this, "Recete kodu boş geçilemez!","UYARI",JOptionPane.WARNING_MESSAGE);

             recete_kodu_field.requestFocus();

             return;
            
        }
        
        boolean kontrol=kod_kontrol(recete_kodu);
        
        if(kontrol==false)
        {
           JOptionPane.showMessageDialog(this, "Böyle bir recete kodu kayıtlarda bulunmamaktadır!","UYARI",JOptionPane.WARNING_MESSAGE); 
           
           recete_kodu_field.requestFocus();
           
           return;
           
        }

        try
        {

            preparedstatement=conn.prepareStatement(sorgu);

            preparedstatement.setString(1,recete_tipi);
            preparedstatement.setString(2,recete_kodu);
            
            preparedstatement.execute();

        }
                       
       
         
         catch (SQLException ex) 
         {
             
           ex.printStackTrace();
           return;
                  
         }
         
        JOptionPane.showMessageDialog(this,"Kayit Başarıyla Güncellendi!");
        
        recete_adi_field.setText("");
        recete_kodu_field.setText("");
        
    }//GEN-LAST:event_guncelle_butonActionPerformed

    private void sil_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_butonActionPerformed
        
        String recete_kodu=recete_kodu_field.getText();
        String recete_tipi=recete_adi_field.getText();

        if(recete_kodu.equals("null"))
        {
            
             JOptionPane.showMessageDialog(this, "Recete kodu boş geçilemez!","UYARI",JOptionPane.WARNING_MESSAGE);

             recete_kodu_field.requestFocus();

             return;
            
        }
        
        boolean kontrol=kod_kontrol(recete_kodu);
        
        if(kontrol==false)
        {
           JOptionPane.showMessageDialog(this, "Böyle bir recete kodu kayıtlarda bulunmamaktadır!","UYARI",JOptionPane.WARNING_MESSAGE); 
           
           recete_kodu_field.requestFocus();
           
           return;
           
        }
        
        try
        {
            recete_kodu = recete_kodu_field.getText();
            
            preparedstatement=conn.prepareStatement(
                    "DELETE FROM receteler"
                            + " WHERE recete_kodu=?");
            
            preparedstatement.setString(1,recete_kodu);
            
            preparedstatement.execute();
        }
        
        catch (SQLException ex) 
        {
           
            String fk_kontol = ex.getMessage();
            
           if(fk_kontol.contains("FK"));   //Foreign Key Hatası
           JOptionPane.showMessageDialog(this, "Silmeye çalıştığınız reçete kodu ilaç tanım tablosunda bulunmaktadır, silemezsiniz!!","UYARI",JOptionPane.WARNING_MESSAGE);
           
           return;
            
        }
        
        
        JOptionPane.showMessageDialog(this,"Kayit Başarıyla Silindi"); 
        
        recete_adi_field.setText("");
        recete_kodu_field.setText("");
        
    }//GEN-LAST:event_sil_butonActionPerformed

    private void recete_kodu_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_recete_kodu_fieldKeyTyped
        
       String metin = recete_kodu_field.getText();
       int uzunluk = metin.length();
       
       char karakter = evt.getKeyChar();
    
       if( !(Character.isDigit(karakter)) || uzunluk == 4 )
        {
         evt.consume();
        }
        
        
    }//GEN-LAST:event_recete_kodu_fieldKeyTyped

    private void recete_adi_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_recete_adi_fieldKeyTyped
        

       char karakter = evt.getKeyChar();
    
       if( (Character.isDigit(karakter))  )
       {
           
        evt.consume();
        
       } 
        
    }//GEN-LAST:event_recete_adi_fieldKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        this.dispose();
        ilac_islem_ekrani ekran = new ilac_islem_ekrani();
        ekran.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean kod_kontrol(String kod)
    {
        
        String sorgu= " Select recete_kodu from "
                + "receteler"
                + " where recete_kodu=?";
        
        
        
        try
        {
            PreparedStatement st = conn.prepareStatement(sorgu);

           
            st.setString(1,kod); //Soru işareti yerine tc gönderiyoruz
           
            ResultSet rs = st.executeQuery();
            
           
            if(rs.next())
            {
                return true;
            }    
            
        } 
        
        
        
        catch (SQLException ex)
        {
             Logger.getLogger(Giris_Ekrani.class.getName()).log(Level.SEVERE, null, ex);
             
        }
        
        return false;
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receteler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receteler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receteler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receteler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new receteler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ekle_buton;
    private javax.swing.JButton getir_buton;
    private javax.swing.JButton guncelle_buton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField recete_adi_field;
    private javax.swing.JTextField recete_kodu_field;
    private javax.swing.JButton sil_buton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
